# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: NativeSync REST API for {{ serviceName }}
  version: "1.0.0"
# the domain of the service
host: api.nativesync.io
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /action/identifier/invoke:
    post:
      summary: Invoke an Action
      description: |
        Invokes a nativesync action
      parameters:
        - name: body
          in: body
          required: true
          schema:
            properties:
              input:
                type: object
                properties:
                  test:
                    type: object
      tags:
        - Action
      responses:
        200:
          description: Output from the action being called
          schema:
            properties:
              output:
                type: object
                properties:
                  test:
                    type: string
              statusCode:
                type: number
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    type: object
    properties:
      error:
        type: string









